### ISSUE TITLE
Anable to launch !

### ISSUE THREAD

**Issue by Mounirsky** [gimenete/dbdiff#19]
dbdiff --help
/usr/local/lib/node_modules/dbdiff/dbdiff.js:6
class DbDiff {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dbdiff/index.js:3:31)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by gimenete** [comment]
Upgrade your Node.js version

**Comment by Mounirsky** [comment]
node --version
v4.2.6

**Comment by Mounirsky** [comment]
It seems ok with v9.5.0 node version.
Thanks
