### ISSUE TITLE
Test fails for constraint

### ISSUE THREAD

**Issue by cellis** [gimenete/dbdiff#23]
Hi, i'm looking into contributing to and using this library as a way of not writing migrations. So far, i've started by running the test suite and ran into this issue:

```sh
  32 passing (5s)
  1 failing

  1) Postgresql should support all constraint types:

      AssertionError [ERR_ASSERTION]: 'CREATE SEQUENCE "public"."items_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;\n\nCREATE SEQUENC == 'CREATE SEQUENCE "public"."users_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;\n\nCREATE SEQUENC
      + expected - actual

      +CREATE SEQUENCE "public"."users_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;
      +
       CREATE SEQUENCE "public"."items_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;

      -CREATE SEQUENCE "public"."users_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;
      -
       CREATE TABLE "public"."users" (
         "id" integer DEFAULT nextval('users_id_seq'::regclass) NOT NULL,
         "email" character varying(255) NULL
       );

      at runCommands.then.then (test/utils.js:35:28)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! Test failed.  See above for more details.
```

Could you tell me which version of PG you're testing against? I'm on 9.6. Thanks!

**Comment by cellis** [comment]
Hmm, after some more investigation, it turns out `dedent` breaks in wierd ways (mac os) with newlines. I was able to fix this by removing dedent from `test-postgres.js` in the . `'should support all constraint types'` block. But i'm not sure of a scalable fix for these types of tests. I like jest snapshots but it would be too complex to use jest on this sort of project. Anyways, will probably submit a PR for this soon.
